[workspace]

members = [
  "rust/tenx-websummary",
  "rust/tenx-websummary-build",
  "rust/tenx-websummary-derive",
  "rust/tenx-websummary-example",
]

exclude = []

resolver = "2"

[profile.release]
codegen-units = 1
debug = 1
lto = true
